spring.application.name=SpringEcom

spring.datasource.url=jdbc:postgresql://localhost:5432/zahiq
spring.datasource.username=postgres
spring.datasource.password= !!add your password here!!

spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.auto-commit=false